# Generated by Django 3.1.6 on 2021-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
