# Generated by Django 3.1.6 on 2021-03-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_answer',
            new_name='my_answer',
        ),
    ]
