# Generated by Django 3.1.6 on 2021-03-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210328_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.answer'),
        ),
    ]
